# Generated by Django 3.2.2 on 2023-01-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('config', models.FileField(upload_to='')),
                ('weights', models.FileField(upload_to='')),
                ('classes', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
